#!/bin/bash

echo "🧪 ASSISTANT ACCÈS SANDBOX PAYTECH"
echo "=================================="

echo ""
echo "📋 VOS INFORMATIONS ACTUELLES :"
echo "==============================="
echo "🔑 API Key: $(grep 'PAYTECH_API_KEY' .env | cut -d'"' -f2 | cut -c1-20)..."
echo "🔐 API Secret: $(grep 'PAYTECH_API_SECRET' .env | cut -d'"' -f2 | cut -c1-20)..."
echo "🌍 Environment: $(grep 'PAYTECH_ENVIRONMENT' .env | cut -d'"' -f2)"
echo "📡 IPN URL: $(grep 'PAYTECH_IPN_URL' .env | cut -d'"' -f2)"

echo ""
echo "🔗 URLS D'ACCÈS PAYTECH :"
echo "========================"
echo "🌐 Site principal: https://www.paytech.sn"
echo "🧪 Sandbox: https://sandbox.paytech.sn"
echo "📊 Dashboard: https://app.paytech.sn"
echo "👤 Login: https://app.paytech.sn/login"

echo ""
echo "💻 MÉTHODES D'ACCÈS AU MODE SANDBOX :"
echo "===================================="
echo ""
echo "1️⃣  VIA LE MENU DÉROULANT :"
echo "   • Connectez-vous à votre dashboard"
echo "   • Cherchez le menu en haut à droite"
echo "   • Sélectionnez 'Mode Test' ou 'Sandbox'"
echo ""
echo "2️⃣  VIA LES PARAMÈTRES :"
echo "   • Allez dans 'Paramètres' > 'Compte'"
echo "   • Cherchez 'Environnement de test'"
echo "   • Activez le mode 'Test/Sandbox'"
echo ""
echo "3️⃣  URL DIRECTE :"
echo "   • https://app.paytech.sn?mode=test"
echo "   • https://sandbox.paytech.sn/dashboard"

echo ""
echo "📊 VOS TRANSACTIONS DE TEST ACTUELLES :"
echo "======================================"
echo "• Transaction 1: https://paytech.sn/payment/checkout/eey3kpmh97ru31 (1000 XOF)"
echo "• Transaction 2: https://paytech.sn/payment/checkout/405gzppmh97ruam (2500 XOF)"
echo "• Transaction 3: https://paytech.sn/payment/checkout/405gzopmh97rujm (10000 XOF)"

echo ""
echo "🎯 ÉTAPES POUR VOIR LES TRANSACTIONS :"
echo "===================================="
echo "1. 📱 Ouvrez votre navigateur et allez sur: https://www.paytech.sn"
echo "2. 🔐 Connectez-vous avec vos identifiants"
echo "3. 🧪 Activez le mode sandbox via une des méthodes ci-dessus"
echo "4. 📊 Allez dans 'Transactions' ou 'Paiements'"
echo "5. 🔍 Filtrez par 'Mode Test' et 'Aujourd'hui'"
echo "6. 💰 Finalisez un paiement via une URL ci-dessus"

echo ""
echo "🆘 SI VOUS NE TROUVEZ PAS LE MODE TEST :"
echo "======================================"
echo "📧 Contactez: support@paytech.sn"
echo "💬 WhatsApp: +221771255799 / +221772457199"
echo "💡 Demandez: 'Activation mode sandbox pour développeur'"

echo ""
echo "✅ VÉRIFICATION :"
echo "================="
echo "• Bandeau jaune/orange = Mode test activé ✅"
echo "• Transactions 'TEST' visibles = OK ✅"
echo "• Paiements finalisables = OK ✅"

echo ""
echo "🚀 MAINTENANT :"
echo "==============="
echo "1. Ouvrez: https://www.paytech.sn"
echo "2. Connectez-vous"
echo "3. Activez le mode test"
echo "4. Finalisez un paiement ci-dessus"

echo ""
echo "📖 Guide complet disponible: ./PAYTECH_SANDBOX_GUIDE.md"